name: caller-testing
on:
  workflow_call:

env:
  GH_TOKEN: ${{ github.token }}
#  POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
  POSTMAN_API_KEY: PMAK-6579143cf938a673eb62ed4e-e019040d8cab3615510f1cefc4befefabe
  REPO_NAME: ${{ github.event.repository.name }}
  APP_ARGS: 'http://localhost:8081 http://localhost:8082 http://localhost:8083'

jobs:
  testing:
    runs-on: latest
    name: Testing Backend
    steps:
      - uses: actions/checkout@v4
      - name: Building with Maven
        run: |
          mvn clean
          mvn package

      - name: Upload Artifact with JAR file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.REPO_NAME }}-JAR-${{ github.run_id }}
          path: target/${{ env.REPO_NAME }}.jar
          
      - name: Download artifact with JAR file
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.REPO_NAME }}-JAR-${{ github.run_id }}
          
      - name: Build Environment
        run: |
          if [ "${{env.REPO_NAME}}" != "orders-service" ]; then
              java -jar ${{ env.REPO_NAME }}.jar         
              mvn -f ${{env.REPO_NAME}}/ -B package
              java -jar ${{env.REPO_NAME}}/target/${{env.REPO_NAME}}.jar --server.port=8081 &
          else
              gh repo clone ORT-FI-8184-TALLER-GRUPO3/products-service           
              mvn -f products-service/ -B package
              java -jar products-service/target/products-service.jar --server.port=8081 &

              gh repo clone ORT-FI-8184-TALLER-GRUPO3/shipping-service           
              mvn -f shipping-service/ -B package
              java -jar shipping-service/target/shipping-service.jar --server.port=8082 &

              gh repo clone ORT-FI-8184-TALLER-GRUPO3/payments-service           
              mvn -f payments-service/ -B package
              java -jar payments-service/target/payments-service.jar --server.port=8083 &

              java -jar ${{ env.REPO_NAME }}.jar 
              mvn -f ${{env.REPO_NAME}}/ -B package
              java -jar ${{env.REPO_NAME}}/target/${{env.REPO_NAME}}.jar ${{ env.APP_ARGS }} --server.port=8084 &
          fi    

      - name: Install Postman CLI
        run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ env.POSTMAN_API_KEY }}

      - name: Get JSON file with Postman Collection
        run: |
          curl -H 'Authorization: token ${{ env.GH_TOKEN }}' \
          -H 'Accept: application/vnd.github.v3.raw' \
          -O -L 'https://raw.githubusercontent.com/ORT-FI-8184-TALLER-GRUPO3/Devops/main/TestingBackend/testing-backend-service.json'

      - name: Run Postman CLI backend testing
        run: 
          postman collection run testing-backend-service.json
