name: Caller CI/CD Workflow

on:
  push:
    branches:
      - Dev
      - Test
      - Prod
  pull_request:
    branches:
      - Dev
      - Test
      - Prod

jobs:
  ReuseableJobForCICD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Invoke Reusable CI/CD Workflow
        uses: ORT-FI-8184-TALLER-GRUPO3/Devops/.github/workflows/cicd.yml@main
        with:
          service: 'products-service'
          target: ${{ github.ref_name }}
          secrets: inherit
 	  pom_path: 'pom.xml'
